SELECT 
    t1.COLUMN_NAME
FROM 
    INFORMATION_SCHEMA.COLUMNS t1
INNER JOIN 
    INFORMATION_SCHEMA.COLUMNS t2 ON t1.COLUMN_NAME = t2.COLUMN_NAME
WHERE 
    t1.TABLE_NAME = 'CLIENT'
    AND t2.TABLE_NAME = 'PAT_CONTRA';
