/*------------------
 * Chaque morceau de requête modifié lui donne un numéro.
 * J'ai laissé ce qui était là avant (original),
 * et la modification est juste après (modifiée).
 */-----------------

SELECT
    IZY_LOC_PERIMETRE.NO_DOSFACT AS 'REFERENCE',
    /* Begin Origin - 01 */
    --CD_HIERAR1,
    /* End Origin - 01 */
    
	/* Begin Modif - 01 */
    LB_SECTEUR,
    /* End Modif - 01 */
    CASE
        WHEN ON_CTRACT1 = 'O' THEN 'CONTRACTANT 1'
        WHEN ON_CTRACT2 = 'O' THEN 'CONTRACTANT 2'
        WHEN ON_CTRACT  = 'O' THEN 'CONTRACTANT ' + CONVERT(VARCHAR, ROW_NUMBER() OVER (PARTITION BY IZY_LOC_PERIMETRE.NO_DOSFACT ORDER BY NO_ORD_CL ASC))
        ELSE ''
    END AS 'CONTACT_ROLE',
    /* Begin Origin - 02 */
--    CASE
--        WHEN SIT_10 = '10' THEN ''
--        ELSE RTRIM(CLIENT.LB_INTCLIE)
--    END AS 'CIVILITE',
    /* End Origin - 02 */
    
    /* Begin Modif - 02 */
    ISNULL(LB_INTCLIE, '') AS 'CIVILITE',
	/* End Modif - 02 */
    
    /* Begin Origin - 03 */
--    CASE
--        WHEN SIT_10 = '10' THEN ISNULL(ADRDF_LIGNE1, '') + ' - tuteur de ' + RTRIM(CLIENT.CD_INTCLIE) + ' ' + UPPER(RTRIM(CLIENT.NOM_CLIENT))
--        ELSE UPPER(RTRIM(CLIENT.NOM_CLIENT))
--    END AS 'NOM',
    /* End Origin - 03 */
    
    /* Begin Modif - 03 */
    CONCAT(COALESCE(ADRDF_NORU, ''), ' ', COALESCE(ADRDF_CDRU, ''), ' ', COALESCE(ADRDF_RUE1, ''), COALESCE(ADRDF_RUE2, '')) AS ADRDF_LIGNE1,
	CASE
	    WHEN COALESCE(CLIENT.ID_TUTEUR, '') <> '' 
	    THEN ISNULL(
	    	CONCAT(COALESCE(ADRDF_NORU, ''), ' ', COALESCE(ADRDF_CDRU, ''), ' ', COALESCE(ADRDF_RUE1, ''), COALESCE(ADRDF_RUE2, '')),
	    '') + ' - tuteur de ' + RTRIM(CLIENT.CD_INTCLIE) + ' ' + UPPER(RTRIM(CLIENT.NOM_CLIENT))
	    ELSE UPPER(RTRIM(CLIENT.NOM_CLIENT))
	END AS 'NOM',
  	/* End Modif - 03 */
    UPPER(RTRIM(CLIENT.PRE_CLIENT)) AS 'PRENOM',
    CASE
        WHEN RTRIM(CTRACT_MAIL) <> ''
        AND (
            RTRIM(CTRACT_MAIL) NOT LIKE '%@%'
            OR RTRIM(CTRACT_MAIL) NOT LIKE '%.%'
            OR RTRIM(CTRACT_MAIL) LIKE '% %'
            OR RTRIM(CTRACT_MAIL) LIKE '%,%'
            OR REVERSE(SUBSTRING(REVERSE(RTRIM(CTRACT_MAIL)), 0, CHARINDEX('.', REVERSE(RTRIM(CTRACT_MAIL)), 0) + 1)) NOT IN ('.fr','.be','.com','.net','.it','.org','.es','.ch')
            /* Begin Origin - 06 */
            --OR SIT_10 = '10'
            /* End Origin - 06 */
            
            /* Begin Modif - 06 */
            OR CLIENT.ID_TUTEUR = '10'
            /* End Modif - 06 */
        )
        THEN ''
        ELSE ISNULL(RTRIM(CTRACT_MAIL), '')
    END AS 'ADRESSE_MAIL',
	CASE
	    WHEN LEN(LTRIM(RTRIM(CTRACT_FIXE))) < 14
	        OR LEN(LTRIM(RTRIM(CTRACT_FIXE))) > 14
	        OR CTRACT_FIXE = '00-00-00-00-00'
	        OR LTRIM(CTRACT_FIXE) NOT LIKE '0%'
	        OR LTRIM(CTRACT_FIXE) LIKE '06%'
	        OR LTRIM(CTRACT_FIXE) LIKE '07%'
	        /* Begin Origin - 04 */
	        --OR SIT_10 = '10'
	        /* End Origin - 04 */
	        
	        /* Begin Modif - 04 */
	        OR CLIENT.ID_TUTEUR = '10'
	        /* Begin Modif - 04 */
	        
	    THEN ''
	    WHEN SUBSTRING(CTRACT_FIXE, 1, 1) = '0'
	    THEN '+33' + SUBSTRING(REPLACE(REPLACE(ISNULL(LTRIM(CTRACT_FIXE), ''), '-', ''), ' ', ''), 2, 10)
	    WHEN LEN(LTRIM(RTRIM(CTRACT_PORT))) = 14
	        AND LTRIM(CTRACT_PORT) NOT LIKE '00%'
	        AND LTRIM(CTRACT_PORT) NOT LIKE '06%'
	        AND LTRIM(CTRACT_PORT) NOT LIKE '07%'
	        AND CTRACT_PORT LIKE '0%'
	    THEN '+33' + SUBSTRING(REPLACE(REPLACE(ISNULL(LTRIM(CTRACT_PORT), ''), '-', ''), ' ', ''), 2, 10)
	    ELSE REPLACE(ISNULL(CTRACT_FIXE, ''), '-', '')
	END AS 'TEL_FIXE',
	 CASE
	    WHEN LEN(LTRIM(RTRIM(CTRACT_PORT))) < 14 OR LEN(LTRIM(RTRIM(CTRACT_PORT))) > 14
	        OR CTRACT_PORT = '00-00-00-00-00'
	        OR LTRIM(CTRACT_PORT) NOT LIKE '0%'
	        OR (CTRACT_PORT NOT LIKE '06%' AND LTRIM(CTRACT_PORT) NOT LIKE '07%')
	        /* Begin Origin - 05 */
	        --OR SIT_10 = '10'
	        /* End Origin - 05 */
	        
	        /* Begin Modif - 05 */
	        OR CLIENT.ID_TUTEUR = '10'
	        /* End Modif - 03 */
	    THEN ''
	    WHEN SUBSTRING(CTRACT_PORT, 1, 1) = '0'
	    THEN '+33' + SUBSTRING(REPLACE(REPLACE(ISNULL(LTRIM(CTRACT_PORT), ''), '-', ''), ' ', ''), 2, 10)
	    WHEN LEN(LTRIM(RTRIM(CTRACT_FIXE))) = 14 AND LTRIM(CTRACT_FIXE) NOT LIKE '00%'
	        AND (LTRIM(CTRACT_FIXE) LIKE '06%' OR LTRIM(CTRACT_FIXE) LIKE '07%')
	        AND LTRIM(CTRACT_FIXE) LIKE '0%'
	    THEN '+33' + SUBSTRING(REPLACE(REPLACE(ISNULL(LTRIM(CTRACT_FIXE), ''), '-', ''), ' ', ''), 2, 10)
	    ELSE REPLACE(ISNULL(CTRACT_PORT, ''), '-', '')
	END AS 'TEL_MOBILE',
    REPLACE(LTRIM(RTRIM(DOSS_FACT.ADRDF_NORU) + ' ' + RTRIM(DOSS_FACT.ADRDF_CDRU) + ' ' + RTRIM(DOSS_FACT.ADRDF_RUE1) + ' ' + RTRIM(DOSS_FACT.ADRDF_RUE2)), ',', '') AS 'ADRESSE_1',
    CASE
        WHEN LEN(RTRIM(DOSS_FACT.ADRDF_CP)) = 4 THEN CONVERT(VARCHAR, '''0' + RTRIM(DOSS_FACT.ADRDF_CP), 5)
        ELSE CONVERT(VARCHAR, RTRIM(DOSS_FACT.ADRDF_CP), 5)
    END AS 'CP',
    RTRIM(DOSS_FACT.ADRDF_LOC) AS 'VILLE',
    'FR' AS 'PAYS',
    REPLACE(CONVERT(VARCHAR, IZY_LOC_PERIMETRE.DT_ALIM, 102), '.', '-') AS 'DATE_DONNEES'
FROM IZY.Cible_locataires IZY_LOC_PERIMETRE

INNER JOIN dbo.DOSS_CLIEN
    ON IZY_LOC_PERIMETRE.CD_SOCIETE = DOSS_CLIEN.CD_SOCIETE
    AND IZY_LOC_PERIMETRE.CD_ACTIVITE = DOSS_CLIEN.CD_ACTIVITE
    AND IZY_LOC_PERIMETRE.ID_DOSCLIE = DOSS_CLIEN.ID_DOSCLIE
    
INNER JOIN dbo.CLIENT
    ON CLIENT.CD_SOCIETE = DOSS_CLIEN.CD_SOCIETE
    AND CLIENT.CD_ACTIVITE = DOSS_CLIEN.CD_ACTIVITE
    AND CLIENT.ID_DOSCLIE = DOSS_CLIEN.ID_DOSCLIE
    AND CLIENT.CD_PHYMOR = 'P'
    AND CLIENT.ON_CTRACT = 'O'
LEFT OUTER JOIN (
    SELECT 
        [ID_DOSCLIE], 
        [CTRACT1_ID] AS 'CTRACT_ID', 
        [CTRACT1_MAIL] AS 'CTRACT_MAIL', 
        [CTRACT1_PORT] AS 'CTRACT_PORT', 
        [CTRACT1_FIXE] AS 'CTRACT_FIXE', 
        [DT_ALIM]
    FROM IZY.IZY_LOCATAIRE_CONTACT_COORDONNEES
    
    UNION
    
    SELECT 
        [ID_DOSCLIE], 
        [CTRACT2_ID] AS 'CTRACT_ID', 
        [CTRACT2_MAIL] AS 'CTRACT_MAIL', 
        [CTRACT2_PORT] AS 'CTRACT_PORT', 
        [CTRACT2_FIXE] AS 'CTRACT_FIXE', 
        [DT_ALIM]
    FROM IZY.IZY_LOCATAIRE_CONTACT_COORDONNEES
    
    UNION
    
    SELECT 
        [ID_DOSCLIE], 
        [CTRACT3_ID] AS 'CTRACT_ID', 
        [CTRACT3_MAIL] AS 'CTRACT_MAIL', 
        [CTRACT3_PORT] AS 'CTRACT_PORT', 
        [CTRACT3_FIXE] AS 'CTRACT_FIXE', 
        [DT_ALIM]
    FROM IZY.IZY_LOCATAIRE_CONTACT_COORDONNEES
    
    UNION
    
    SELECT 
        [ID_DOSCLIE], 
        [CTRACT4_ID] AS 'CTRACT_ID', 
        [CTRACT4_MAIL] AS 'CTRACT_MAIL', 
        [CTRACT4_PORT] AS 'CTRACT_PORT', 
        [CTRACT4_FIXE] AS 'CTRACT_FIXE', 
        [DT_ALIM]
    FROM IZY.IZY_LOCATAIRE_CONTACT_COORDONNEES
) IZY_LOCATAIRE_CONTACT_COORDONNEES

ON CLIENT.ID_DOSCLIE = IZY_LOCATAIRE_CONTACT_COORDONNEES.ID_DOSCLIE
AND CLIENT.ID_CLIENT = IZY_LOCATAIRE_CONTACT_COORDONNEES.CTRACT_ID
AND IZY_LOCATAIRE_CONTACT_COORDONNEES.CTRACT_ID <> 0

INNER JOIN dbo.DOSS_FACT
ON IZY_LOC_PERIMETRE.CD_SOCIETE = DOSS_FACT.CD_SOCIETE
AND IZY_LOC_PERIMETRE.CD_ACTIVITE = DOSS_FACT.CD_ACTIVITE
AND IZY_LOC_PERIMETRE.ID_DOSCLIE = DOSS_FACT.ID_DOSCLIE
AND IZY_LOC_PERIMETRE.NO_DOSFACT = DOSS_FACT.NO_DOSFACT

--LEFT OUTER JOIN dbo.DOSS_FACT_CPL2
--ON IZY_LOC_PERIMETRE.CD_SOCIETE = DOSS_FACT_CPL2.CD_SOCIETE
--AND IZY_LOC_PERIMETRE.CD_ACTIVITE = DOSS_FACT_CPL2.CD_ACTIVITE
--AND IZY_LOC_PERIMETRE.NO_DOSFACT = DOSS_FACT_CPL2.NO_DOSFACT
--
--WHERE ISNULL(SIT_8600, '') <> '8600' -- sans situations >= 8600 actives
--AND ISNULL(SIT_1700, '') <> '1700' -- sans situation 1700 active

ORDER BY 1, 2;